/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soundcloud;

import java.io.File;
import java.sql.ResultSet;
import javafx.scene.media.MediaPlayer;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ibrahim
 */
public class ReviewSong extends javax.swing.JFrame {
    DBConnection conn = DBConnection.getInstance();
    DefaultTableModel dtm;
    ResultSet x;
    boolean delete;
      private static MediaPlayer mp;
    String path="Music\\";
    private static Music_player mmp;
    CustomerService cs = CustomerService.getInstance("Ibrahim", "3553", "dg4534", "c3453c5c3");
    /**
     * Creates new form ReviewSong
     */
    public ReviewSong() {
        delete = false;
        this.setResizable(false);
        x = conn.getAllFeedback();
        dtm = DBConnection.buildTableModel(x);
        initComponents();
        this.welcome.setText("Welcome "+ cs.name);

    }
    public ReviewSong(CustomerService cust) {
        cs = cust;
        this.welcome.setText("Welcome "+cs.name);
        delete = false;
        this.setResizable(false);
        x = conn.getAllFeedback();
        dtm = DBConnection.buildTableModel(x);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bg1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        feedback = new JTable(dtm);
        feedbackdetails = new javax.swing.JButton();
        review = new javax.swing.JButton();
        resolveIssue = new javax.swing.JButton();
        del = new javax.swing.JRadioButton();
        dontdel = new javax.swing.JRadioButton();
        welcome = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bg1.add(del);bg1.add(dontdel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(feedback);

        feedbackdetails.setText("View FeedbackDetails");
        feedbackdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackdetailsActionPerformed(evt);
            }
        });

        review.setText("Review Song");
        review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewActionPerformed(evt);
            }
        });

        resolveIssue.setText("Resolve Issue");
        resolveIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolveIssueActionPerformed(evt);
            }
        });

        del.setText("Delete Song");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        dontdel.setText("Do not Delete Song");
        dontdel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dontdelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dontdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dontdelActionPerformed(evt);
            }
        });

        welcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcome.setText("Welcome");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/soundcloud/Capture8.PNG"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(feedbackdetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(review, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(del)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dontdel))
                            .addComponent(resolveIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(del)
                        .addComponent(dontdel))
                    .addComponent(review, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resolveIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(feedbackdetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feedbackdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackdetailsActionPerformed
        // TODO add your handling code here:
        this.feedback.setRowSelectionAllowed(true);
        int selected_row = this.feedback.getSelectedRow();
        int id = (int) this.feedback.getValueAt(selected_row, 0);
        String details = (String) this.feedback.getValueAt(selected_row, 1);
        String song = (String) this.feedback.getValueAt(selected_row, 2);
        String date = (String) this.feedback.getValueAt(selected_row, 3);
        String user = (String) this.feedback.getValueAt(selected_row, 4);
        
        JLabel[] arr = {new JLabel("FeedbackID: "+Integer.toString(id)), new JLabel("Song: "+song), new JLabel("Submitted by: "+user), new JLabel("Submitted on: "+date), new JLabel("Description: "+details)};
        
        JOptionPane.showMessageDialog(null, arr);
    }//GEN-LAST:event_feedbackdetailsActionPerformed

    private void reviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewActionPerformed
        // TODO add your handling code here:        
        this.feedback.setRowSelectionAllowed(true);
        int selected_row = this.feedback.getSelectedRow();
        String song = (String) this.feedback.getValueAt(selected_row, 2);
        int song_id = conn.getSongID(song);
        boolean status = cs.reviewCopyrights(song_id);
        Song s = conn.retrieveSong(song_id);
        String path = "Music\\" + s.path_to_file;        
        mmp=new Music_player( mp,path);
        mmp.setVisible(true);        
    }//GEN-LAST:event_reviewActionPerformed

    private void resolveIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolveIssueActionPerformed
        // TODO add your handling code here:
        JDialog.setDefaultLookAndFeelDecorated(true);
        this.feedback.setRowSelectionAllowed(true);
        int selected_row = this.feedback.getSelectedRow();
        String song = (String) this.feedback.getValueAt(selected_row, 2);
        int song_id = conn.getSongID(song);
        Feedback fb = cs.getSongFeedback(song_id);
        if (delete==true)
        {
            int response = JOptionPane.showConfirmDialog(null, "You selected Delete song. Are you sure you want to delete this Song?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) 
            {
                Song my_song = conn.retrieveSong(song_id);
                cs.SongViolatesCommunityGuidelines(fb, song_id);
                File file = new File( "C:\\Users\\Ali Arshad\\Documents\\NetBeansProjects\\SoundCloud\\Music\\"+my_song.path_to_file);
                file.delete();
                int user_id = my_song.added_by;
                JOptionPane.showMessageDialog(rootPane, "Song " + song + " has been deleted.");
                User uss = conn.getUser(user_id);
                String [] Email  = new String[1];
                Email[0] = uss.email;
        
                String message = "The following song has been deleted. \n Song: "+ my_song.title +"\n Genre: "+my_song.Genre+"\n Description: "+my_song.Description+"\n\n\n\n Thankyou for using SoundCloud!";
                conn.sendEmail(SoundCloud.my_email, SoundCloud.my_pass, Email, "Violation of Community Guidelines", message);
                JOptionPane.showMessageDialog(rootPane, "Email notification sent to " + uss.email + ".");
            } 
        }
        else
        {
            int response = JOptionPane.showConfirmDialog(null, "You selected Do not Delete song.", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) 
            {
                cs.SongDoesNotViolateCommunityGuidelines(fb, song_id);
                JOptionPane.showMessageDialog(rootPane, "Issue has been resolved.");
            }
        }
        this.dispose();
        ReviewSong rev = new ReviewSong();
        rev.setVisible(true);
    }//GEN-LAST:event_resolveIssueActionPerformed

    private void dontdelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dontdelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_dontdelAncestorAdded

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        delete = true;
    }//GEN-LAST:event_delActionPerformed

    private void dontdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dontdelActionPerformed
        delete = false;
    }//GEN-LAST:event_dontdelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ManageAccounts ma = new ManageAccounts();
        ma.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewSong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JRadioButton del;
    private javax.swing.JRadioButton dontdel;
    private javax.swing.JTable feedback;
    private javax.swing.JButton feedbackdetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton resolveIssue;
    private javax.swing.JButton review;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
